# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.310networks.com
title: Daniel Ryan
email: daniel.ryan@310networks.com
author: Daniel Ryan
description: >
  My name is Daniel Ryan and I like making and playing with things.
#copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  categories:
    output: true

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    url: mailto:daniel.ryan@310networks.com
  - title: github
    url: https://github.com/Kookster310/
  - title: linkedin
    url: https://www.linkedin.com/in/daniel-ryan-310/
  - title: resume
    url: https://docs.google.com/document/d/1m-ODLGnpdVB58fdDJEOuEKJokZ56wulxvQAMZNaTwjI
