site_name: Daniel Ryan
site_url: https://www.310networks.com

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: slate
    primary: blue
    accent: blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top

nav:
  - Home: index.md
  - Posts:
      - Overview: posts/index.md
      - "An Agent for Home Part 2": posts/an-agent-for-home-pt2.md
      - An Agent for Home: posts/an-agent-for-home.md
      - National General Strike: posts/national-general-strike.md
      - Fresh year, fresh thoughts: posts/fresh-year-fresh-thoughts.md
      - 3D Printing: posts/3d-printing.md
      - Crypto Mining - The New-Age 49er: posts/crypto-mining-new-age-49er.md
      - DN42 - A Big Dynamic VPN: posts/dn42-big-dynamic-vpn.md
      - Ansible Deployments - Automate Everything: posts/ansible-deployments.md
      - PiHole - Home DNS Server for Ad Blocking and Traffic Analysis: posts/pi-hole-home-dns.md
  - Audio Dramas:
      - Overview: audio-dramas/index.md
      - "DC High Volume: Batman - Review": audio-dramas/dc-high-volume-batman.md
  - Bits: bits/index.md

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:daniel.ryan@310networks.com
    - icon: fontawesome/brands/github
      link: https://github.com/Kookster310/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daniel-ryan-310/
    - icon: fontawesome/solid/file
      link: https://docs.google.com/document/d/1m-ODLGnpdVB58fdDJEOuEKJokZ56wulxvQAMZNaTwjI

extra_css:
  - assets/extra.css

plugins:
  - search

hooks:
  - hooks.py
